---
title: "Cyclone reef effects"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(vegan)
library(ggplot2)
library(dplyr)
library(gridExtra)
library(cowplot)
setwd("~/Projects/R_analysis_phd")
source("summarySE.R")
```



```{r}
benthic.data <- read.csv("~/Projects/R_analysis_phd/sargassaceae_all benthic categories for graphs summed coral.csv", strip.white=T)

# Rename site labels
benthic.data$Site <- factor(benthic.data$Site, 
                            levels=c("Turtle North - Back", "Turtle North - Coral", 
                         "Turtle North - Front", "Turtle South - Channel", "Turtle South - Coral", 
                         "Turtle South - Front"), 
                         labels=c("North - Back", "North - Coral", "North - Front", "South - Channel", "South - Back", "South - Front"))

benthic.data <- benthic.data %>% gather(key=Organism, value=Abundance, Acropora:Zoantharian...Green)

str(benthic.data)

benthic.summary <- summarySE(benthic.data, measurevar = "Abundance", groupvars = c("Year", "Site", "Organism"))

str(benthic.summary)

(coral <- benthic.summary
    %>% filter(Site %in% c("South - Back", "North - Back"), Organism == "Coral")
    %>% ggplot(aes(x = Year, y = Abundance, col = Site))
    + ggtitle("Coral")
    + geom_point()
    + geom_line()
    + geom_linerange(aes(ymin = Abundance - se, ymax = Abundance + se))
    + ylab("Abundance (% cover)")
    + ylim(0,80)
    + scale_color_manual(values = c("#990099", "#FF0033"))
    + theme_classic() 
    + theme(axis.title.x = element_blank(), axis.text.x = element_blank(), 
            text = element_text(size = 14), plot.margin = unit(c(0, 0, 0, 0), "cm"), 
            plot.title = element_text(size = 16, hjust = 0.5)))

(sargassum <- benthic.summary 
    %>% filter(Site %in% c("South - Front", "North - Front"), Organism=="Sargassaceae")   
    %>% ggplot(aes(x = Year, y = Abundance, col = Site))
    + ggtitle("Seaweed")
    + geom_point()
    + geom_line()
    + geom_linerange(aes(ymin = Abundance - se, ymax = Abundance + se))
    + ylab("Abundance (% cover)")
    + ylim(0,80)
    + scale_color_manual(values = c("#003300","#339900"))
    + theme_classic()
    + theme(text = element_text(size = 14), plot.margin = unit(c(0, 0, 0, 0), "cm"), 
            plot.title = element_text(size = 16, hjust = 0.5)))

(coral.vs.sargassum <-  plot_grid(coral, sargassum, ncol = 1,labels = c("a","b"), label_fontface = "bold", align = "hv"))

#ggsave(file = 'coral.vs.sargassum.eps', coral.vs.sargassum, width=10,height=15,dpi=200, units='cm')
```

```{r}
benthic_data_for_pca <- read.csv('~/Projects/R_analysis_phd/all benthic categories for multivariate.csv', strip.white = T)

str(benthic_data_for_pca)

benthic_data_for_pca <- benthic_data_for_pca %>%
  mutate(Year = as.factor(Year), Transect = as.factor(Transect))

benthic_data_for_pca$Site <- factor(benthic_data_for_pca$Site, 
                                    levels = c("Turtle North - Back", "Turtle North - Coral",   
                                             "Turtle North - Front", "Turtle South - Channel", 
                                             "Turtle South - Coral", "Turtle South - Front"),
                                    labels = c("NB" ,   "NC",   "NF",   "SCh", "SC", "SF"))

benthic.long <- benthic_data_for_pca %>% 
  gather(key = Organism, value = Abundance, Hard.coral:Zoantharian...Green)

benthic.avg <- benthic.long %>% 
  group_by(yr.si, Year, Site, Organism) %>% 
  dplyr:::summarise(avg.abundance = mean(Abundance))

benthic_data_for_pca <- benthic.avg %>% 
  spread(key = Organism, value = avg.abundance) %>% as.data.frame()

benthic.rda <- rda(benthic_data_for_pca[,-1:-3], scale=F)

summary(benthic.rda, display=NULL)

screeplot(benthic.rda)

benthic.yr.si.scores <- as.data.frame(scores(benthic.rda, choices=1:3, display='sites'))
benthic.yr.si.scores <- data.frame(benthic.yr.si.scores, benthic_data_for_pca)
benthic.species.scores <- as.data.frame(scores(benthic.rda, choices=1:3, display = 'species'))
benthic.species.scores$Species <- rownames(benthic.species.scores)

hjust <- ifelse(pointstolabel$PC1>0,0,1)
vjust <- ifelse(pointstolabel$PC2>0,0,1)

(dots.plot <- ggplot() 
  + geom_point(data = benthic.yr.si.scores, aes(y = PC2, x=PC1)) 
  + geom_text(data = benthic.yr.si.scores, aes(y = PC2, x = PC1, label = Year, 
                                               hjust = -0.2, color = Site)) 
  + scale_x_continuous(limits = c(-9,5))+scale_y_continuous(limits = c(-5, 10)))


pointstolabel <- benthic.species.scores %>% 
  select(PC1, PC2, PC3, Species) %>% 
  filter(Species %in% c("Halicoyrne", "Sargassum", "Hard.coral", "Rubble", "Padina", "Chnoospora", 
                        "Sand.Rubble","Pavement", "Dictyota", "Halimeda", "Valonia"))

(arrow.plot <- ggplot() 
  + geom_segment(data = benthic.species.scores, aes(y = 0, x = 0, yend = PC2, xend = PC1), 
                 arrow = arrow(length = unit(0.3,'lines'))) 
  + geom_text(aes(y=PC2, x=PC1, label=Species), data = pointstolabel, hjust = hjust, vjust = vjust)
  + scale_x_continuous(limits = c(-9,5))
  + scale_y_continuous(limits = c(-5, 10)))

(benthic_pca <- ggplot()
  + geom_point(data = benthic.yr.si.scores, aes(y = PC2, x = PC1, color = Year))
  + geom_text(data = benthic.yr.si.scores, aes(y = PC2, x = PC1, label = Site, hjust = -0.2, 
                                             color = Year), show.legend = F)
  + geom_segment(data = benthic.species.scores, aes(y = 0, x = 0, yend = PC2, xend = PC1), 
               arrow = arrow(length = unit(0.3,'lines'))))

benthic_pca <- benthic_pca + 
  geom_text(aes(y = PC2, x = PC1, label = Species), data = pointstolabel, 
            hjust = hjust, vjust = vjust) + 
  geom_segment(data = NULL, aes(y = 0,x = -Inf, yend = 0, xend = Inf), linetype='dotted') +
  geom_segment(data = NULL, aes(y = -Inf, x = 0, yend = Inf, xend = 0),
               linetype='dotted') + 
  theme_bw()

benthic.hull <-  benthic.yr.si.scores %>% 
  group_by(Year) %>%
  do({
    data.frame(.[chull(.$PC1,.$PC2),])
  })

(benthic_pca = benthic_pca + 
    geom_polygon(data = benthic.hull, aes(y = PC2, x = PC1, fill = Year, color = Year), 
                 alpha = 0.2) + 
    scale_color_manual(values = c("#A3A500","#00BF7D","#00B0F6","#E76BF3","#F8766D")) +
    scale_fill_manual(values = c("#A3A500","#00BF7D","#00B0F6","#E76BF3","#F8766D")))


eig <- eigenvals(benthic.rda)

benthic_pca <-  benthic_pca + 
  scale_y_continuous(paste(names(eig[2]), sprintf('(%0.1f%% explained var.)', 
                                                  100 * eig[2]/sum(eig)))) + 
  scale_x_continuous(paste(names(eig[1]), sprintf('(%0.1f%% explained var.)', 
                                                  100 * eig[1]/sum(eig))), limits=c(-10, 8))


benthic_pca <- benthic_pca + theme(text = element_text(size=14),legend.position = c(0.80,0.95),
           legend.justification = c(0,1)) + theme_classic()
benthic_pca
```

